### ISSUE TITLE
Loss of precision after calculating a portion of the mesh?

### ISSUE THREAD

**Issue by sjrc6** [tdhooper/glsl-marching-cubes#1]
I know this project is super old but if this bug was fixed it would significantly improve the usability for me.

It seems like after a certain amount of the mesh is calculated it loses precision, even the default sphere seems to have this issue when processed at 500x500x500. 

![image](https://user-images.githubusercontent.com/22122579/126574765-05ba8e34-4a6e-46e0-85bd-859ca9cc511f.png)
![image](https://user-images.githubusercontent.com/22122579/126574831-50f806f7-5cd2-4c9f-bfeb-24cb27fa5cfb.png)

**Comment by Emanuele-Spatola** [comment]
@tdhooper do you have any idea on what is causing this issue? If you point me to the right direction I will try to find a fix.
